--
-- PostgreSQL database dump
--

\restrict IkNzG5k0Fhobw2VTa9WfFhFlAtUqZQ6tJntnl46NCOtrmQF7tH96uqOg8B3IvG8

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg13+1)
-- Dumped by pg_dump version 18.4

-- Started on 2026-09-22 10:19:08

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 256 (class 1255 OID 16902)
-- Name: kiem_tra_ton_kho(integer, integer); Type: FUNCTION; Schema: public; Owner: cuong
--

CREATE FUNCTION public.kiem_tra_ton_kho(p_ma_bien_the integer, p_so_luong_dat integer) RETURNS boolean
    LANGUAGE plpgsql
    AS $$
DECLARE
    v_so_luong_ton INT;
    v_ten_sp VARCHAR;
BEGIN
    -- Lấy số lượng tồn kho và tên sản phẩm từ bảng ProductVariant và Product
    SELECT spbt.SoLuongTon, sp.TenSP
    INTO v_so_luong_ton, v_ten_sp
    FROM SanPhamBienThe spbt
    JOIN SanPham sp ON spbt.MaSP = sp.MaSP
    WHERE spbt.MaBienThe = p_ma_bien_the;

    -- Kiểm tra xem mã biến thể có tồn tại không
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Không tìm thấy sản phẩm biến thể với mã: %', p_ma_bien_the;
    END IF;

    -- Kiểm tra số lượng tồn so với số lượng đặt
    IF v_so_luong_ton < p_so_luong_dat THEN
        RAISE EXCEPTION 'Sản phẩm "%" không đủ số lượng. Tồn kho hiện tại chỉ còn: %', v_ten_sp, v_so_luong_ton;
    END IF;

    RETURN TRUE;
END;
$$;


ALTER FUNCTION public.kiem_tra_ton_kho(p_ma_bien_the integer, p_so_luong_dat integer) OWNER TO cuong;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16515)
-- Name: blacklisted_tokens; Type: TABLE; Schema: public; Owner: cuong
--

CREATE TABLE public.blacklisted_tokens (
    id bigint NOT NULL,
    blacklisted_at timestamp(6) without time zone,
    token character varying(512) NOT NULL
);


ALTER TABLE public.blacklisted_tokens OWNER TO cuong;

--
-- TOC entry 219 (class 1259 OID 16514)
-- Name: blacklisted_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: cuong
--

ALTER TABLE public.blacklisted_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blacklisted_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 16878)
-- Name: chitietdonhang; Type: TABLE; Schema: public; Owner: cuong
--

CREATE TABLE public.chitietdonhang (
    machitiet integer NOT NULL,
    madonhang integer NOT NULL,
    mabienthe integer NOT NULL,
    soluong integer,
    dongia numeric(12,2),
    thanhtien numeric(12,2) GENERATED ALWAYS AS (((soluong)::numeric * dongia)) STORED,
    CONSTRAINT chitietdonhang_soluong_check CHECK ((soluong > 0))
);


ALTER TABLE public.chitietdonhang OWNER TO cuong;

--
-- TOC entry 239 (class 1259 OID 16877)
-- Name: chitietdonhang_machitiet_seq; Type: SEQUENCE; Schema: public; Owner: cuong
--

CREATE SEQUENCE public.chitietdonhang_machitiet_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.chitietdonhang_machitiet_seq OWNER TO cuong;

--
-- TOC entry 3596 (class 0 OID 0)
-- Dependencies: 239
-- Name: chitietdonhang_machitiet_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cuong
--

ALTER SEQUENCE public.chitietdonhang_machitiet_seq OWNED BY public.chitietdonhang.machitiet;


--
-- TOC entry 224 (class 1259 OID 16745)
-- Name: danhmuc; Type: TABLE; Schema: public; Owner: cuong
--

CREATE TABLE public.danhmuc (
    madm integer NOT NULL,
    tendm character varying(100) NOT NULL,
    mota character varying(200)
);


ALTER TABLE public.danhmuc OWNER TO cuong;

--
-- TOC entry 223 (class 1259 OID 16744)
-- Name: danhmuc_madm_seq; Type: SEQUENCE; Schema: public; Owner: cuong
--

CREATE SEQUENCE public.danhmuc_madm_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.danhmuc_madm_seq OWNER TO cuong;

--
-- TOC entry 3597 (class 0 OID 0)
-- Dependencies: 223
-- Name: danhmuc_madm_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cuong
--

ALTER SEQUENCE public.danhmuc_madm_seq OWNED BY public.danhmuc.madm;


--
-- TOC entry 238 (class 1259 OID 16858)
-- Name: donhang; Type: TABLE; Schema: public; Owner: cuong
--

CREATE TABLE public.donhang (
    madonhang integer NOT NULL,
    id integer NOT NULL,
    tennguoinhan character varying(100) NOT NULL,
    sodienthoainhan character varying(20) NOT NULL,
    diachigiaohang character varying(255) NOT NULL,
    phuongthucthanhtoan character varying(50),
    ngaydat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    tongtien numeric(12,2),
    trangthai character varying(50) DEFAULT 'Chờ duyệt'::character varying,
    momo_order_id character varying(50),
    CONSTRAINT donhang_trangthai_check CHECK (((trangthai)::text = ANY ((ARRAY['Chờ duyệt'::character varying, 'Đang giao'::character varying, 'Hoàn thành'::character varying, 'Hủy'::character varying])::text[])))
);


ALTER TABLE public.donhang OWNER TO cuong;

--
-- TOC entry 237 (class 1259 OID 16857)
-- Name: donhang_madonhang_seq; Type: SEQUENCE; Schema: public; Owner: cuong
--

CREATE SEQUENCE public.donhang_madonhang_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.donhang_madonhang_seq OWNER TO cuong;

--
-- TOC entry 3598 (class 0 OID 0)
-- Dependencies: 237
-- Name: donhang_madonhang_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cuong
--

ALTER SEQUENCE public.donhang_madonhang_seq OWNED BY public.donhang.madonhang;


--
-- TOC entry 236 (class 1259 OID 16835)
-- Name: giohang; Type: TABLE; Schema: public; Owner: cuong
--

CREATE TABLE public.giohang (
    magiohang integer NOT NULL,
    id integer NOT NULL,
    mabienthe integer NOT NULL,
    soluong integer DEFAULT 1,
    ngaythem timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT giohang_soluong_check CHECK ((soluong > 0))
);


ALTER TABLE public.giohang OWNER TO cuong;

--
-- TOC entry 235 (class 1259 OID 16834)
-- Name: giohang_magiohang_seq; Type: SEQUENCE; Schema: public; Owner: cuong
--

CREATE SEQUENCE public.giohang_magiohang_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.giohang_magiohang_seq OWNER TO cuong;

--
-- TOC entry 3599 (class 0 OID 0)
-- Dependencies: 235
-- Name: giohang_magiohang_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cuong
--

ALTER SEQUENCE public.giohang_magiohang_seq OWNED BY public.giohang.magiohang;


--
-- TOC entry 234 (class 1259 OID 16820)
-- Name: hinhanhsanpham; Type: TABLE; Schema: public; Owner: cuong
--

CREATE TABLE public.hinhanhsanpham (
    mahinhanh integer NOT NULL,
    masp integer NOT NULL,
    duongdan character varying(255) NOT NULL
);


ALTER TABLE public.hinhanhsanpham OWNER TO cuong;

--
-- TOC entry 233 (class 1259 OID 16819)
-- Name: hinhanhsanpham_mahinhanh_seq; Type: SEQUENCE; Schema: public; Owner: cuong
--

CREATE SEQUENCE public.hinhanhsanpham_mahinhanh_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.hinhanhsanpham_mahinhanh_seq OWNER TO cuong;

--
-- TOC entry 3600 (class 0 OID 0)
-- Dependencies: 233
-- Name: hinhanhsanpham_mahinhanh_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cuong
--

ALTER SEQUENCE public.hinhanhsanpham_mahinhanh_seq OWNED BY public.hinhanhsanpham.mahinhanh;


--
-- TOC entry 244 (class 1259 OID 17031)
-- Name: lienhe; Type: TABLE; Schema: public; Owner: cuong
--

CREATE TABLE public.lienhe (
    id bigint NOT NULL,
    content character varying(255),
    receiver character varying(255),
    sender character varying(255),
    "timestamp" timestamp(6) without time zone
);


ALTER TABLE public.lienhe OWNER TO cuong;

--
-- TOC entry 243 (class 1259 OID 17030)
-- Name: lienhe_id_seq; Type: SEQUENCE; Schema: public; Owner: cuong
--

ALTER TABLE public.lienhe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lienhe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16781)
-- Name: mausac; Type: TABLE; Schema: public; Owner: cuong
--

CREATE TABLE public.mausac (
    mamau integer NOT NULL,
    tenmau character varying(50) NOT NULL,
    mamauhex character varying(7) NOT NULL
);


ALTER TABLE public.mausac OWNER TO cuong;

--
-- TOC entry 229 (class 1259 OID 16780)
-- Name: mausac_mamau_seq; Type: SEQUENCE; Schema: public; Owner: cuong
--

CREATE SEQUENCE public.mausac_mamau_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.mausac_mamau_seq OWNER TO cuong;

--
-- TOC entry 3601 (class 0 OID 0)
-- Dependencies: 229
-- Name: mausac_mamau_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cuong
--

ALTER SEQUENCE public.mausac_mamau_seq OWNED BY public.mausac.mamau;


--
-- TOC entry 222 (class 1259 OID 16725)
-- Name: nguoidung; Type: TABLE; Schema: public; Owner: cuong
--

CREATE TABLE public.nguoidung (
    id integer NOT NULL,
    hoten character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    matkhau character varying(255) NOT NULL,
    sodienthoai character varying(20),
    diachi character varying(200),
    vaitro character varying(20) DEFAULT 'User'::character varying,
    ngaytao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    trangthai boolean DEFAULT true,
    is_guest boolean,
    CONSTRAINT nguoidung_vaitro_check CHECK (((vaitro)::text = ANY ((ARRAY['Admin'::character varying, 'Employee'::character varying, 'User'::character varying])::text[])))
);


ALTER TABLE public.nguoidung OWNER TO cuong;

--
-- TOC entry 221 (class 1259 OID 16724)
-- Name: nguoidung_id_seq; Type: SEQUENCE; Schema: public; Owner: cuong
--

CREATE SEQUENCE public.nguoidung_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.nguoidung_id_seq OWNER TO cuong;

--
-- TOC entry 3602 (class 0 OID 0)
-- Dependencies: 221
-- Name: nguoidung_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cuong
--

ALTER SEQUENCE public.nguoidung_id_seq OWNED BY public.nguoidung.id;


--
-- TOC entry 226 (class 1259 OID 16754)
-- Name: sanpham; Type: TABLE; Schema: public; Owner: cuong
--

CREATE TABLE public.sanpham (
    masp integer NOT NULL,
    tensp character varying(150) NOT NULL,
    madm integer,
    giaban numeric(12,2),
    giakhuyenmai numeric(12,2),
    mota text,
    hinhanh character varying(255),
    ngaythem timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT sanpham_giaban_check CHECK ((giaban >= (0)::numeric))
);


ALTER TABLE public.sanpham OWNER TO cuong;

--
-- TOC entry 225 (class 1259 OID 16753)
-- Name: sanpham_masp_seq; Type: SEQUENCE; Schema: public; Owner: cuong
--

CREATE SEQUENCE public.sanpham_masp_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.sanpham_masp_seq OWNER TO cuong;

--
-- TOC entry 3603 (class 0 OID 0)
-- Dependencies: 225
-- Name: sanpham_masp_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cuong
--

ALTER SEQUENCE public.sanpham_masp_seq OWNED BY public.sanpham.masp;


--
-- TOC entry 232 (class 1259 OID 16791)
-- Name: sanphambienthe; Type: TABLE; Schema: public; Owner: cuong
--

CREATE TABLE public.sanphambienthe (
    mabienthe integer NOT NULL,
    masp integer NOT NULL,
    masize integer NOT NULL,
    mamau integer NOT NULL,
    soluongton integer DEFAULT 0,
    giaban numeric(12,2),
    CONSTRAINT sanphambienthe_giaban_check CHECK ((giaban >= (0)::numeric)),
    CONSTRAINT sanphambienthe_soluongton_check CHECK ((soluongton >= 0))
);


ALTER TABLE public.sanphambienthe OWNER TO cuong;

--
-- TOC entry 231 (class 1259 OID 16790)
-- Name: sanphambienthe_mabienthe_seq; Type: SEQUENCE; Schema: public; Owner: cuong
--

CREATE SEQUENCE public.sanphambienthe_mabienthe_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.sanphambienthe_mabienthe_seq OWNER TO cuong;

--
-- TOC entry 3604 (class 0 OID 0)
-- Dependencies: 231
-- Name: sanphambienthe_mabienthe_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cuong
--

ALTER SEQUENCE public.sanphambienthe_mabienthe_seq OWNED BY public.sanphambienthe.mabienthe;


--
-- TOC entry 228 (class 1259 OID 16772)
-- Name: size; Type: TABLE; Schema: public; Owner: cuong
--

CREATE TABLE public.size (
    masize integer NOT NULL,
    tensize character varying(10) NOT NULL
);


ALTER TABLE public.size OWNER TO cuong;

--
-- TOC entry 227 (class 1259 OID 16771)
-- Name: size_masize_seq; Type: SEQUENCE; Schema: public; Owner: cuong
--

CREATE SEQUENCE public.size_masize_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.size_masize_seq OWNER TO cuong;

--
-- TOC entry 3605 (class 0 OID 0)
-- Dependencies: 227
-- Name: size_masize_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cuong
--

ALTER SEQUENCE public.size_masize_seq OWNED BY public.size.masize;


--
-- TOC entry 242 (class 1259 OID 17014)
-- Name: thongbao; Type: TABLE; Schema: public; Owner: cuong
--

CREATE TABLE public.thongbao (
    mathongbao integer NOT NULL,
    dadoc boolean NOT NULL,
    madonhang integer NOT NULL,
    thoigian timestamp(6) without time zone NOT NULL,
    trangthai character varying(50) NOT NULL,
    id integer NOT NULL
);


ALTER TABLE public.thongbao OWNER TO cuong;

--
-- TOC entry 241 (class 1259 OID 17013)
-- Name: thongbao_mathongbao_seq; Type: SEQUENCE; Schema: public; Owner: cuong
--

ALTER TABLE public.thongbao ALTER COLUMN mathongbao ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.thongbao_mathongbao_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3368 (class 2604 OID 16881)
-- Name: chitietdonhang machitiet; Type: DEFAULT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.chitietdonhang ALTER COLUMN machitiet SET DEFAULT nextval('public.chitietdonhang_machitiet_seq'::regclass);


--
-- TOC entry 3354 (class 2604 OID 16748)
-- Name: danhmuc madm; Type: DEFAULT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.danhmuc ALTER COLUMN madm SET DEFAULT nextval('public.danhmuc_madm_seq'::regclass);


--
-- TOC entry 3365 (class 2604 OID 16861)
-- Name: donhang madonhang; Type: DEFAULT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.donhang ALTER COLUMN madonhang SET DEFAULT nextval('public.donhang_madonhang_seq'::regclass);


--
-- TOC entry 3362 (class 2604 OID 16838)
-- Name: giohang magiohang; Type: DEFAULT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.giohang ALTER COLUMN magiohang SET DEFAULT nextval('public.giohang_magiohang_seq'::regclass);


--
-- TOC entry 3361 (class 2604 OID 16823)
-- Name: hinhanhsanpham mahinhanh; Type: DEFAULT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.hinhanhsanpham ALTER COLUMN mahinhanh SET DEFAULT nextval('public.hinhanhsanpham_mahinhanh_seq'::regclass);


--
-- TOC entry 3358 (class 2604 OID 16784)
-- Name: mausac mamau; Type: DEFAULT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.mausac ALTER COLUMN mamau SET DEFAULT nextval('public.mausac_mamau_seq'::regclass);


--
-- TOC entry 3350 (class 2604 OID 16728)
-- Name: nguoidung id; Type: DEFAULT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.nguoidung ALTER COLUMN id SET DEFAULT nextval('public.nguoidung_id_seq'::regclass);


--
-- TOC entry 3355 (class 2604 OID 16757)
-- Name: sanpham masp; Type: DEFAULT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.sanpham ALTER COLUMN masp SET DEFAULT nextval('public.sanpham_masp_seq'::regclass);


--
-- TOC entry 3359 (class 2604 OID 16794)
-- Name: sanphambienthe mabienthe; Type: DEFAULT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.sanphambienthe ALTER COLUMN mabienthe SET DEFAULT nextval('public.sanphambienthe_mabienthe_seq'::regclass);


--
-- TOC entry 3357 (class 2604 OID 16775)
-- Name: size masize; Type: DEFAULT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.size ALTER COLUMN masize SET DEFAULT nextval('public.size_masize_seq'::regclass);


--
-- TOC entry 3566 (class 0 OID 16515)
-- Dependencies: 220
-- Data for Name: blacklisted_tokens; Type: TABLE DATA; Schema: public; Owner: cuong
--

COPY public.blacklisted_tokens (id, blacklisted_at, token) FROM stdin;
1	2026-08-15 23:45:07.46832	eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3ODY4MTIyOTcsImV4cCI6MTc4Njg5ODY5N30.gF4wsBYa3_cUYyEwOzFKxqgeyLVX0JBQgSd-nbuyEsIO1XJvTijBR63ndUKre78Z
2	2026-08-15 23:57:10.559297	eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3ODY4MTMwMTgsImV4cCI6MTc4Njg5OTQxOH0.bTSqu-YoWV8IPjr6bcb9Nv-ANfMcmMQ5KdDfQQleDQe2wn80ZwN0Y2UAeWIb6YqL
\.


--
-- TOC entry 3586 (class 0 OID 16878)
-- Dependencies: 240
-- Data for Name: chitietdonhang; Type: TABLE DATA; Schema: public; Owner: cuong
--

COPY public.chitietdonhang (machitiet, madonhang, mabienthe, soluong, dongia) FROM stdin;
2	2	875	1	380000.00
3	3	811	3	890000.00
4	4	811	1	890000.00
7	7	967	2	270000.00
8	8	1131	3	540000.00
9	9	787	1	720000.00
10	10	816	1	590000.00
11	11	788	1	720000.00
12	12	780	1	650000.00
13	13	784	1	780000.00
\.


--
-- TOC entry 3570 (class 0 OID 16745)
-- Dependencies: 224
-- Data for Name: danhmuc; Type: TABLE DATA; Schema: public; Owner: cuong
--

COPY public.danhmuc (madm, tendm, mota) FROM stdin;
1	Áo Khoác Nam	Các loại áo khoác gió, áo blazer, áo bomber dành cho nam.
2	Áo Khoác Nữ	Áo khoác nữ thời trang, phù hợp cho đi làm và dạo phố.
3	Áo Len Nữ	Áo len ấm áp, phong cách trẻ trung cho nữ.
4	Áo Polo Nam	Áo polo nam cao cấp, lịch sự và dễ phối đồ.
5	Áo Sơ Mi Nam	Áo sơ mi nam công sở, thanh lịch và hiện đại.
6	Áo Sơ Mi Nữ	Áo sơ mi nữ thời trang, phù hợp nhiều phong cách.
7	Áo Thun Nam	Áo thun nam năng động, thoải mái cho hàng ngày.
8	Áo Thun Nữ	Áo thun nữ trẻ trung, nhiều mẫu mã đa dạng.
9	Đầm Nữ	Các loại đầm dự tiệc, dạo phố và công sở dành cho nữ.
10	Phụ Kiện	Thắt lưng, ví da, túi xách, mũ và nhiều phụ kiện khác.
11	Quần Jean Nam	Quần jean nam cá tính, chất liệu bền đẹp.
12	Quần Short Nam	Quần short nam thoải mái, phù hợp đi chơi và thể thao.
13	Quần Tây Nam	Quần tây nam lịch lãm, phù hợp công sở và sự kiện.
14	Váy Nữ	Váy thời trang nữ, phong cách đa dạng từ công sở đến dự tiệc.
15	áo đá banh	áo đá banh MUFC
\.


--
-- TOC entry 3584 (class 0 OID 16858)
-- Dependencies: 238
-- Data for Name: donhang; Type: TABLE DATA; Schema: public; Owner: cuong
--

COPY public.donhang (madonhang, id, tennguoinhan, sodienthoainhan, diachigiaohang, phuongthucthanhtoan, ngaydat, tongtien, trangthai, momo_order_id) FROM stdin;
13	3	jgh	546457457	gfhf	MOMO	2026-09-18 09:25:24.814408	780000.00	Hủy	MOMO1789698325073
7	3	văn anh	0987563828	bình tân 	MOMO	2026-09-04 09:15:45.442257	540000.00	Hủy	MOMO1788488145674
8	3	phát	0494888478	bình tân tân phú	MOMO	2026-09-04 15:23:23.270206	1620000.00	Hủy	MOMO1788510203428
10	7	hiển	0484948984	lê trọng tấn	COD	2026-09-04 22:36:01.660346	590000.00	Hủy	\N
9	3	ai	0992904948	tân phú tây thạnh	COD	2026-09-04 16:31:05.687673	720000.00	Hủy	\N
4	3	văn a	0498488498	hồ chí minh	COD	2026-08-30 15:39:23.973825	890000.00	Hoàn thành	\N
3	3	hiền	0948494893	tây thạnh tân phú	MOMO	2026-08-30 15:04:53.577413	2670000.00	Hủy	MOMO1788077093774
11	7	tôi	049488429	tân bình	MOMO	2026-09-08 16:51:15.721258	720000.00	Hủy	MOMO1788861075882
12	3	qđ	049432882	tân phú	COD	2026-09-15 08:50:40.632709	650000.00	Chờ duyệt	\N
2	3	cương nguyễn	0493988483	lê trọng tấn tân phú	COD	2026-08-30 13:28:35.847955	380000.00	Đang giao	\N
\.


--
-- TOC entry 3582 (class 0 OID 16835)
-- Dependencies: 236
-- Data for Name: giohang; Type: TABLE DATA; Schema: public; Owner: cuong
--

COPY public.giohang (magiohang, id, mabienthe, soluong, ngaythem) FROM stdin;
15	3	780	1	2026-09-08 08:50:00.373053
\.


--
-- TOC entry 3580 (class 0 OID 16820)
-- Dependencies: 234
-- Data for Name: hinhanhsanpham; Type: TABLE DATA; Schema: public; Owner: cuong
--

COPY public.hinhanhsanpham (mahinhanh, masp, duongdan) FROM stdin;
1	1	aokhoacnam_1.jpg
2	2	aokhoacnu_1.jpg
3	3	aolennu_1.jpg
4	4	aopolonam_1.jpg
5	5	aosominam_1.jpg
6	6	aosominu_1.jpg
7	7	aothunnam_1.jpg
8	8	aothunnu_1.jpg
9	9	dam_1.jpg
10	10	non_1.jpg
11	11	tui_1.jpg
12	12	quanjeannam_1.jpg
13	13	quanshortnam_1.jpg
14	14	quantaynam_1.jpg
15	15	vay_1.jpg
\.


--
-- TOC entry 3590 (class 0 OID 17031)
-- Dependencies: 244
-- Data for Name: lienhe; Type: TABLE DATA; Schema: public; Owner: cuong
--

COPY public.lienhe (id, content, receiver, sender, "timestamp") FROM stdin;
7	chào shop	STAFF_INBOX	hien@gmail.com	2026-09-11 10:03:00.767282
8	chào bạn, bạn cần giúp đỡ gì	hien@gmail.com	admin@gmail.com	2026-09-11 10:03:34.286635
9	bạn muốn mua sản phẩm gì	hien@gmail.com	admin@gmail.com	2026-09-11 10:07:13.275556
10	tôi muốn mua áo khoác	STAFF_INBOX	hien@gmail.com	2026-09-11 10:08:33.925275
11	chào shop tôi cần hỗ trợ	STAFF_INBOX	cuongcathung@gmail.com	2026-09-11 10:41:33.661706
12	tôi muốn mua áo khoác	STAFF_INBOX	cuongcathung@gmail.com	2026-09-11 10:42:21.324023
13	bạn chọn mẫu áo khoác nào gửi tôi tư vấn	hien@gmail.com	admin@gmail.com	2026-09-11 15:25:39.136729
14	áo màu đen mình có mẫu nào	STAFF_INBOX	hien@gmail.com	2026-09-11 15:26:11.448258
15	bạn gửi tôi vài hình mẫu đi	STAFF_INBOX	hien@gmail.com	2026-09-11 15:26:37.716098
16	chào buổi sáng shop nha	STAFF_INBOX	hien@gmail.com	2026-09-15 08:26:42.813203
17	chào bạn cần giúp gì	hien@gmail.com	admin@gmail.com	2026-09-15 08:27:49.862471
18	tôi muốn mua áo khoác vào mùa đông	STAFF_INBOX	hien@gmail.com	2026-09-15 08:39:34.979395
19	chào shop sao chưa vấn sản phẩm cho tôi	STAFF_INBOX	cuongcathung@gmail.com	2026-09-15 08:40:09.673554
20	shop chúng tôi có nhiều áo khoác mùa đông rất hợp	hien@gmail.com	admin@gmail.com	2026-09-15 08:40:48.311695
21	xin lỗi bạn	cuongcathung@gmail.com	admin@gmail.com	2026-09-15 08:41:12.410164
22	ok shop	STAFF_INBOX	cuongcathung@gmail.com	2026-09-15 08:43:55.225478
23	để tôi gửi hình cho bạn	cuongcathung@gmail.com	admin@gmail.com	2026-09-15 08:44:09.739833
24	đây	cuongcathung@gmail.com	admin@gmail.com	2026-09-15 08:45:22.625049
25	hình đây bạn	cuongcathung@gmail.com	admin@gmail.com	2026-09-15 08:48:59.475051
26	để tôi xem	STAFF_INBOX	cuongcathung@gmail.com	2026-09-15 08:49:11.761776
27	tôi chon mẫu số 1	STAFF_INBOX	cuongcathung@gmail.com	2026-09-15 08:49:39.333918
28	bạn đâu r	hien@gmail.com	admin@gmail.com	2026-09-15 08:49:56.678509
29	tôi đây	hien@gmail.com	admin@gmail.com	2026-09-15 08:51:11.600246
30	fjhhjf	STAFF_INBOX	hien@gmail.com	2026-09-15 08:53:29.725859
31	hjdjd	cuongcathung@gmail.com	admin@gmail.com	2026-09-15 08:53:40.268489
32	fđf	hien@gmail.com	admin@gmail.com	2026-09-15 08:53:47.021595
33	a	hien@gmail.com	admin@gmail.com	2026-09-15 08:57:46.932184
34	ab	cuongcathung@gmail.com	admin@gmail.com	2026-09-15 08:57:58.414265
35	abc	cuongcathung@gmail.com	admin@gmail.com	2026-09-15 08:58:07.839012
36	jh	hien@gmail.com	admin@gmail.com	2026-09-15 08:58:18.635989
37	h	hien@gmail.com	admin@gmail.com	2026-09-15 10:07:02.526202
38	ad	hien@gmail.com	admin@gmail.com	2026-09-15 10:12:19.357779
39	sd	hien@gmail.com	admin@gmail.com	2026-09-15 10:14:12.391739
40	dgfgf	cuongcathung@gmail.com	admin@gmail.com	2026-09-15 10:15:21.004327
41	chào	STAFF_INBOX	guest_2018_895874e851@guest.local	2026-09-17 23:19:48.216152
42	chào b	guest_2018_895874e851@guest.local	admin@gmail.com	2026-09-17 23:21:10.302563
43	tôi mua áo	STAFF_INBOX	guest_2018_895874e851@guest.local	2026-09-17 23:21:29.673085
44	áo khoác màu đen	STAFF_INBOX	guest_2018_895874e851@guest.local	2026-09-17 23:30:30.068993
45	a	STAFF_INBOX	guest_2018_895874e851@guest.local	2026-09-17 23:53:01.279145
46	chào shop	STAFF_INBOX	guest_3721_f24da1d616@guest.local	2026-09-22 08:26:32.697719
47	chào bạn bạn cần gì	guest_3721_f24da1d616@guest.local	admin@gmail.com	2026-09-22 08:28:08.157885
\.


--
-- TOC entry 3576 (class 0 OID 16781)
-- Dependencies: 230
-- Data for Name: mausac; Type: TABLE DATA; Schema: public; Owner: cuong
--

COPY public.mausac (mamau, tenmau, mamauhex) FROM stdin;
1	Xám	#808080
2	Nâu	#8B4513
3	Hồng	#FFC0CB
4	Xanh rêu	#556B2F
5	Vàng	#FFD700
6	Tím	#800080
7	Cam	#FFA500
8	Xanh ngọc	#48D1CC
9	Be	#F5F5DC
10	Đỏ đô	#8B0000
11	Xanh biển	#0000FF
12	Xanh lá	#008000
13	Nâu nhạt	#CD853F
14	Đen bóng	#000000
15	Trắng kem	#FFFDD0
16	Hồng pastel	#FFD1DC
17	Xanh tím than	#191970
18	Vàng đồng	#B8860B
19	Xám bạc	#C0C0C0
20	Xanh navy	#000080
\.


--
-- TOC entry 3568 (class 0 OID 16725)
-- Dependencies: 222
-- Data for Name: nguoidung; Type: TABLE DATA; Schema: public; Owner: cuong
--

COPY public.nguoidung (id, hoten, email, matkhau, sodienthoai, diachi, vaitro, ngaytao, trangthai, is_guest) FROM stdin;
4	Trần Văn A	vana@gmail.com	$2a$10$6wncVkvfzS9XXY4448OboOvdhfp63rrne3IZsPYmHlEAXTl0ETYYa	0984783929	Hồ Chí Minh	User	2026-08-30 15:23:19.060274	\N	\N
3	Nguyễn Thị Thu Hiền	hien@gmail.com	$2a$10$t6y7IwDdHGvp9sfHFhkt8eeNNvNG2WfeSrEJyVEZYWk/BitxU.C32	0943984839	Bình Định	User	2026-08-29 21:32:48.560206	t	\N
2	Nguyễn Xuân Cương	admin@gmail.com	$2a$10$DbMU7kOPiHbm8Mp7wen70eVyrWxNuel8tssR9uuVnoaz652XmdWJW	0393849302	Tân Phú	Admin	2026-08-29 17:04:43.639898	t	\N
7	xuân cương nguyễn	cuongcathung@gmail.com	$2a$10$yBH/FBK5uW9bKBmWeZfpEOPeg/2ruaHKnUlsl08jAr5qczP7u6iXG	\N	\N	User	2026-09-04 21:46:54.49171	t	\N
8	Khách 0340	guest_0340_f983a8a770@guest.local	$2a$10$43dbFCRRD8.3Oil5waD6AOY7HzsQXHQqAzcla296SobgROZdQ2Hn2	\N	\N	User	2026-09-17 23:16:48.029922	t	t
9	Khách 2018	guest_2018_895874e851@guest.local	$2a$10$W82.3F4PIiUIjpb4xe4K5e9EI5JDYTBHNojDx0MmyyWTIvgPfaV.2	\N	\N	User	2026-09-17 23:17:29.116138	t	t
10	Khách 8255	guest_8255_4a161a8a54@guest.local	$2a$10$iuP8mhN2gbRyurbqrm.fWOeEzCtArTPL7kZgeGU94JxA2LKk/vc6e	\N	\N	User	2026-09-17 23:20:02.113447	t	t
11	Khách 2935	guest_2935_444ff9c3fe@guest.local	$2a$10$.XWZsA64MAhp0xHgksfb0eVso1tXv/J5Nll/J9SxSpQdm6YSvfFse	\N	\N	User	2026-09-18 09:25:43.015918	t	t
12	Khách 3721	guest_3721_f24da1d616@guest.local	$2a$10$ODx2CQiEtZMPoQ73QvJ4KeFcjTu/YjqAipnFUpswVDIlX8fexd0h6	\N	\N	User	2026-09-22 08:21:31.285114	t	t
13	Khách 6420	guest_6420_12c1ee05f0@guest.local	$2a$10$NocQDPiOQWnceMYaX09y3e19mB7D3pjUaCIHGxpoQAgchXSNIVCF2	\N	\N	User	2026-09-22 08:24:23.108841	t	t
\.


--
-- TOC entry 3572 (class 0 OID 16754)
-- Dependencies: 226
-- Data for Name: sanpham; Type: TABLE DATA; Schema: public; Owner: cuong
--

COPY public.sanpham (masp, tensp, madm, giaban, giakhuyenmai, mota, hinhanh, ngaythem) FROM stdin;
1	Áo khoác bomber nam đen	1	650000.00	\N	Chất liệu kaki cao cấp, giữ ấm tốt.	aokhoacnam_1.jpg	2026-08-29 07:09:22.085396
2	Áo blazer nam lịch lãm	1	780000.00	\N	Phong cách công sở, form slimfit.	aokhoacnam_2.jpg	2026-08-29 07:09:22.085396
3	Áo khoác gió nam chống nước	1	720000.00	\N	Dễ giặt, khô nhanh, phù hợp đi chơi.	aokhoacnam_3.jpg	2026-08-29 07:09:22.085396
4	Áo khoác da nam cá tính	1	950000.00	\N	Chất liệu da PU mềm, sang trọng.	aokhoacnam_4.jpg	2026-08-29 07:09:22.085396
5	Áo khoác kaki nam cổ đứng	1	690000.00	\N	Phong cách trẻ trung, lịch lãm.	aokhoacnam_5.jpg	2026-08-29 07:09:22.085396
6	Áo khoác có nón dây kéo	1	569000.00	\N	Chất liệu kaki cao cấp, giữ ấm tốt.	aokhoacnam_6.jpg	2026-08-29 07:09:22.085396
7	Áo khoác bomber nam da lộn	1	785000.00	\N	Phong cách công sở, form slimfit.	aokhoacnam_7.jpg	2026-08-29 07:09:22.085396
8	Áo khoác nam dài tay chần bông có túi form loose	1	981000.00	\N	Dễ giặt, khô nhanh, phù hợp đi chơi.	aokhoacnam_8.jpg	2026-08-29 07:09:22.085396
9	Áo khoác không cổ chần bông mỏng form loose	1	686000.00	\N	Chất liệu da PU mềm, sang trọng.	aokhoacnam_9.jpg	2026-08-29 07:09:22.085396
10	Áo khoác denim nam form loose	1	512000.00	\N	Phong cách trẻ trung, lịch lãm.	aokhoacnam_10.jpg	2026-08-29 07:09:22.085396
11	Áo khoác dạ nữ dài	2	890000.00	\N	Kiểu dáng Hàn Quốc, tôn dáng.	aokhoacnu_1.jpg	2026-08-29 07:09:22.085396
12	Áo khoác gió nữ có mũ	2	590000.00	\N	Chống nắng, chống nước, nhẹ.	aokhoacnu_2.jpg	2026-08-29 07:09:22.085396
13	Áo khoác len nữ oversize	2	620000.00	\N	Phong cách trẻ trung, dễ phối đồ.	aokhoacnu_3.jpg	2026-08-29 07:09:22.085396
14	Áo khoác lông nữ thời trang	2	970000.00	\N	Giữ ấm cực tốt, mềm mịn.	aokhoacnu_4.jpg	2026-08-29 07:09:22.085396
15	Áo khoác dù nữ dáng ngắn	2	650000.00	\N	Phù hợp cho mùa thu, năng động.	aokhoacnu_5.jpg	2026-08-29 07:09:22.085396
16	Áo Khoác Tay Dài Nữ Cao Cổ Phối Màu Form Loosei	2	490000.00	\N	Kiểu dáng Hàn Quốc, tôn dáng.	aokhoacnu_6.jpg	2026-08-29 07:09:22.085396
17	Áo khoác thể thao nữ chống tia UV bo chun loose	2	501000.00	\N	Chống nắng, chống nước, nhẹ.	aokhoacnu_7.jpg	2026-08-29 07:09:22.085396
18	Áo phao nữ chần bông cổ rời form regular	2	686000.00	\N	Phong cách trẻ trung, dễ phối đồ.	aokhoacnu_8.jpg	2026-08-29 07:09:22.085396
19	Áo khoác nữ cổ vest form Regular cropped	2	149000.00	\N	Giữ ấm cực tốt, mềm mịn.	aokhoacnu_9.jpg	2026-08-29 07:09:22.085396
20	Áo khoác nữ túi đắp	2	490000.00	\N	Phù hợp cho mùa thu, năng động.	aokhoacnu_10.jpg	2026-08-29 07:09:22.085396
21	Áo len cổ lọ nữ	3	480000.00	\N	Giữ ấm, phù hợp mùa đông.	aolennu_1.jpg	2026-08-29 07:09:22.085396
22	Áo len dệt kim tay dài	3	420000.00	\N	Chất len mềm, thoải mái.	aolennu_2.jpg	2026-08-29 07:09:22.085396
23	Áo len nữ form rộng	3	460000.00	\N	Hợp thời trang, dễ phối quần jean.	aolennu_3.jpg	2026-08-29 07:09:22.085396
24	Áo len croptop nữ	3	390000.00	\N	Phong cách năng động, trẻ trung.	aolennu_4.jpg	2026-08-29 07:09:22.085396
25	Áo len cổ tròn nữ pastel	3	440000.00	\N	Màu nhẹ nhàng, tinh tế.	aolennu_5.jpg	2026-08-29 07:09:22.085396
26	Áo dệt kim tay ngắn nữ cổ tròn kẻ sọc. Fitted	3	274000.00	\N	Giữ ấm, phù hợp mùa đông.	aolennu_6.jpg	2026-08-29 07:09:22.085396
27	Áo dệt kim nữ phối lai tay	3	422000.00	\N	Chất len mềm, thoải mái.	aolennu_7.jpg	2026-08-29 07:09:22.085396
28	Áo polo nam trơn cổ bẻ	4	350000.00	\N	Vải cotton co giãn 4 chiều.	aopolonam_1.jpg	2026-08-29 07:09:22.085396
29	Áo polo nam sọc caro	4	380000.00	\N	Thiết kế hiện đại, thoáng mát.	aopolonam_2.jpg	2026-08-29 07:09:22.085396
30	Áo polo nam tay ngắn	4	320000.00	\N	Phù hợp đi làm và dạo phố.	aopolonam_3.jpg	2026-08-29 07:09:22.085396
31	Áo polo nam phối màu	4	370000.00	\N	Phong cách trẻ trung, nam tính.	aopolonam_4.jpg	2026-08-29 07:09:22.085396
32	Áo polo nam thể thao	4	400000.00	\N	Thiết kế thoáng khí, co giãn tốt.	aopolonam_5.jpg	2026-08-29 07:09:22.085396
33	Áo Polo dệt kim tay dài nam	4	687000.00	\N	Vải cotton co giãn 4 chiều.	aopolonam_6.jpg	2026-08-29 07:09:22.085396
34	Áo polo tay ngắn nam phối cổ	4	589000.00	\N	Thiết kế hiện đại, thoáng mát.	aopolonam_7.jpg	2026-08-29 07:09:22.085396
35	Áo polo premium nam bo tay lịch lãm	4	349000.00	\N	Phù hợp đi làm và dạo phố.	aopolonam_8.jpg	2026-08-29 07:09:22.085396
36	Áo polo nam tay ngắn sọc phối patch	4	618000.00	\N	Phong cách trẻ trung, nam tính.	aopolonam_9.jpg	2026-08-29 07:09:22.085396
37	Áo Polo Nam Tay Ngắn Cotton Túi Đắp Phối Thêu	4	490000.00	\N	Thiết kế thoáng khí, co giãn tốt.	aopolonam_10.jpg	2026-08-29 07:09:22.085396
38	Áo sơ mi nam trắng công sở	5	420000.00	\N	Form ôm body, vải mát.	aosominam_1.jpg	2026-08-29 07:09:22.085396
39	Áo sơ mi nam caro đỏ	5	450000.00	\N	Phong cách năng động, lịch sự.	aosominam_2.jpg	2026-08-29 07:09:22.085396
40	Áo sơ mi nam denim	5	480000.00	\N	Vải jean mềm, cổ bẻ.	aosominam_3.jpg	2026-08-29 07:09:22.085396
41	Áo sơ mi nam tay dài đen	5	440000.00	\N	Phù hợp môi trường làm việc.	aosominam_4.jpg	2026-08-29 07:09:22.085396
42	Áo sơ mi nam họa tiết sọc dọc	5	460000.00	\N	Tạo cảm giác cao ráo, hiện đại.	aosominam_5.jpg	2026-08-29 07:09:22.085396
43	Áo sơ mi tay dài nam vải flannel	5	667000.00	\N	Form ôm body, vải mát.	aosominam_6.jpg	2026-08-29 07:09:22.085396
44	Áo Sơ Mi Nam Smart shirt Tay Dài Kẻ Sọc. Boxy	5	540000.00	\N	Phong cách năng động, lịch sự.	aosominam_7.jpg	2026-08-29 07:09:22.085396
45	Áo Sơ Mi Nam Smart shirt Tay Dài Cổ Button Down	5	399000.00	\N	Vải jean mềm, cổ bẻ.	aosominam_8.jpg	2026-08-29 07:09:22.085396
46	Áo Sơ Mi Nam Smart shirt Tay Ngắn Cổ Gài Nút	5	349000.00	\N	Phù hợp môi trường làm việc.	aosominam_9.jpg	2026-08-29 07:09:22.085396
47	Áo sơ mi nam dài tay cotton cổ trụ form fitted	5	469000.00	\N	Tạo cảm giác cao ráo, hiện đại.	aosominam_10.jpg	2026-08-29 07:09:22.085396
48	Áo sơ mi nữ tay phồng	6	390000.00	\N	Thiết kế thanh lịch, hiện đại.	aosominu_1.jpg	2026-08-29 07:09:22.085396
49	Áo sơ mi nữ cổ nơ	6	420000.00	\N	Phù hợp công sở và dự tiệc.	aosominu_2.jpg	2026-08-29 07:09:22.085396
50	Áo sơ mi nữ trắng cổ tròn	6	370000.00	\N	Chất liệu mát, dễ giặt.	aosominu_3.jpg	2026-08-29 07:09:22.085396
51	Áo sơ mi nữ họa tiết hoa	6	410000.00	\N	Phong cách nhẹ nhàng, nữ tính.	aosominu_4.jpg	2026-08-29 07:09:22.085396
52	Áo sơ mi nữ cổ bèo	6	430000.00	\N	Thiết kế điệu đà, tôn dáng.	aosominu_5.jpg	2026-08-29 07:09:22.085396
53	Áo sơ mi tay ngắn nữ vải texture	6	249000.00	\N	Thiết kế thanh lịch, hiện đại.	aosominu_6.jpg	2026-08-29 07:09:22.085396
54	Áo sơ mi tay phồng nữ	6	441000.00	\N	Phù hợp công sở và dự tiệc.	aosominu_7.jpg	2026-08-29 07:09:22.085396
55	Áo Sơ Mi Nữ Crop Tay Dài Cotton Kẻ Sọc Form Rộng	6	471000.00	\N	Chất liệu mát, dễ giặt.	aosominu_8.jpg	2026-08-29 07:09:22.085396
56	Áo Sơ Mi Crop Nữ Tay Dài Kẻ Sọc Caro Dây Cột Eo	6	308000.00	\N	Phong cách nhẹ nhàng, nữ tính.	aosominu_9.jpg	2026-08-29 07:09:22.085396
57	Áo Sơ Mi Nữ Tay Dài Cotton Kẻ Sọc Form Loose	6	431000.00	\N	Thiết kế điệu đà, tôn dáng.	aosominu_10.jpg	2026-08-29 07:09:22.085396
58	Áo thun nam trơn cổ tròn	7	250000.00	\N	Vải cotton thoáng mát.	aothunnam_1.jpg	2026-08-29 07:09:22.085396
59	Áo thun nam in hình	7	270000.00	\N	In 3D hiện đại, bền màu.	aothunnam_2.jpg	2026-08-29 07:09:22.085396
60	Áo thun nam cổ tim	7	260000.00	\N	Đơn giản, dễ phối đồ.	aothunnam_3.jpg	2026-08-29 07:09:22.085396
61	Áo thun nam thể thao	7	290000.00	\N	Thoát mồ hôi nhanh, co giãn tốt.	aothunnam_4.jpg	2026-08-29 07:09:22.085396
62	Áo thun nam basic trơn	7	240000.00	\N	Phong cách tối giản, dễ mặc.	aothunnam_5.jpg	2026-08-29 07:09:22.085396
63	Áo thun tay dài nam sọc ngang	7	638000.00	\N	Vải cotton thoáng mát.	aothunnam_6.jpg	2026-08-29 07:09:22.085396
64	Áo thun nam tay ngắn sọc phối patch	7	589000.00	\N	In 3D hiện đại, bền màu.	aothunnam_7.jpg	2026-08-29 07:09:22.085396
65	Áo thun tay ngắn nam túi đắp hình thêu	7	392000.00	\N	Đơn giản, dễ phối đồ.	aothunnam_8.jpg	2026-08-29 07:09:22.085396
66	Áo thun giá tốt basic trơn tay ngắn	7	147000.00	\N	Thoát mồ hôi nhanh, co giãn tốt.	aothunnam_9.jpg	2026-08-29 07:09:22.085396
67	Áo thun tay ngắn nam nỉ phối vai	7	441000.00	\N	Phong cách tối giản, dễ mặc.	aothunnam_10.jpg	2026-08-29 07:09:22.085396
68	Áo thun nữ croptop	8	260000.00	\N	Phong cách cá tính, năng động.	aothunnu_1.jpg	2026-08-29 07:09:22.085396
69	Áo thun nữ tay ngắn	8	240000.00	\N	Mềm mại, co giãn tốt.	aothunnu_2.jpg	2026-08-29 07:09:22.085396
70	Áo thun nữ in chữ	8	250000.00	\N	Thiết kế trẻ trung, thời trang.	aothunnu_3.jpg	2026-08-29 07:09:22.085396
71	Áo thun nữ cổ tim	8	230000.00	\N	Tối giản, dễ phối quần jean.	aothunnu_4.jpg	2026-08-29 07:09:22.085396
72	Áo thun nữ oversize pastel	8	270000.00	\N	Màu nhẹ, trẻ trung, dễ thương.	aothunnu_5.jpg	2026-08-29 07:09:22.085396
73	Áo thun tay dài nữ	8	441000.00	\N	Phong cách cá tính, năng động.	aothunnu_6.jpg	2026-08-29 07:09:22.085396
74	Áo polo Slimme phối viền	8	471000.00	\N	Mềm mại, co giãn tốt.	aothunnu_7.jpg	2026-08-29 07:09:22.085396
75	Áo thun tay ngắn nữ nhãn metal	8	294000.00	\N	Thiết kế trẻ trung, thời trang.	aothunnu_8.jpg	2026-08-29 07:09:22.085396
76	Áo polo Slimme diễu tay	8	343000.00	\N	Tối giản, dễ phối quần jean.	aothunnu_9.jpg	2026-08-29 07:09:22.085396
77	Áo thun Slimme Cổ vuông thêu logo	8	342000.00	\N	Màu nhẹ, trẻ trung, dễ thương.	aothunnu_10.jpg	2026-08-29 07:09:22.085396
78	Đầm công sở ôm body	9	580000.00	\N	Chất vải cao cấp, tôn dáng.	dam_1.jpg	2026-08-29 07:09:22.085396
79	Đầm maxi đi biển	9	620000.00	\N	Họa tiết hoa nhí, nhẹ nhàng.	dam_2.jpg	2026-08-29 07:09:22.085396
80	Đầm suông tay ngắn	9	540000.00	\N	Dễ mặc, phù hợp nhiều hoàn cảnh.	dam_3.jpg	2026-08-29 07:09:22.085396
81	Đầm dự tiệc ánh kim	9	850000.00	\N	Lấp lánh, sang trọng, cuốn hút.	dam_4.jpg	2026-08-29 07:09:22.085396
82	Đầm xếp ly midi	9	590000.00	\N	Phong cách thanh lịch, dịu dàng.	dam_5.jpg	2026-08-29 07:09:22.085396
83	Đầm thun Slimme raglan xẻ trước	9	378000.00	\N	Chất vải cao cấp, tôn dáng.	dam_6.jpg	2026-08-29 07:09:22.085396
84	Đầm thun Slimme cổ V phối viền	9	569000.00	\N	Họa tiết hoa nhí, nhẹ nhàng.	dam_7.jpg	2026-08-29 07:09:22.085396
85	Đầm dài nữ tay ngắn cotton có túi form a line	9	199000.00	\N	Dễ mặc, phù hợp nhiều hoàn cảnh.	dam_8.jpg	2026-08-29 07:09:22.085396
86	Đầm dài sơ mi nữ tay ngắn kẻ sọc form loose	9	638000.00	\N	Lấp lánh, sang trọng, cuốn hút.	dam_9.jpg	2026-08-29 07:09:22.085396
87	Đầm polo nữ form straight	9	189000.00	\N	Phong cách thanh lịch, dịu dàng.	dam_10.jpg	2026-08-29 07:09:22.085396
88	Nón da nam cao cấp	10	380000.00	\N	Chất liệu da mềm, chống thấm nhẹ, tôn vẻ lịch lãm cho phái mạnh.	non_1.jpg	2026-08-29 07:09:22.085396
89	Nón jean phong cách	10	420000.00	\N	Thiết kế cá tính, dễ phối đồ, phù hợp đi chơi và dạo phố.	non_2.jpg	2026-08-29 07:09:22.085396
90	Nón bucket thời trang	10	250000.00	\N	Kiểu dáng unisex, thích hợp cho cả nam và nữ, che nắng hiệu quả.	non_3.jpg	2026-08-29 07:09:22.085396
91	Nón tay bèo rộng phong cách	10	340000.00	\N	Phù hợp cho du lịch biển, tạo phong cách nữ tính và trẻ trung.	non_4.jpg	2026-08-29 07:09:22.085396
92	Nón lưỡi trai thời trang	10	460000.00	\N	Thiết kế năng động, giúp bảo vệ tốt dưới ánh nắng mặt trời.	non_5.jpg	2026-08-29 07:09:22.085396
93	Túi da nam cao cấp	10	38000.00	\N	Chất da thật bền bỉ, thiết kế sang trọng, phù hợp môi trường công sở.	tui_1.jpg	2026-08-29 07:09:22.085396
94	Túi thắt lưng da trơn	10	42000.00	\N	Kiểu dáng nhỏ gọn, tiện lợi khi di chuyển, tôn phong cách nam tính.	tui_2.jpg	2026-08-29 07:09:22.085396
95	Túi bucket thời trang	10	25000.00	\N	Phong cách trẻ trung, có dây rút, thích hợp đi chơi hoặc dạo phố.	tui_3.jpg	2026-08-29 07:09:22.085396
96	Túi đeo chéo mini	10	34000.00	\N	Gọn nhẹ, tiện lợi để điện thoại, ví tiền, phù hợp cho cả nam và nữ.	tui_4.jpg	2026-08-29 07:09:22.085396
97	Túi balo canvas trẻ trung	10	46000.00	\N	Chất vải dày bền, phong cách năng động, phù hợp học sinh và dân văn phòng.	tui_5.jpg	2026-08-29 07:09:22.085396
98	Túi Tote Vải Canvas Size Vừa In Hình	10	49000.00	\N	Gọn nhẹ, tiện lợi để điện thoại, ví tiền, phù hợp cho cả nam và nữ.	tui_6.jpg	2026-08-29 07:09:22.085396
99	Túi Tote Brewing Dream	10	780000.00	\N	Chất vải dày bền, phong cách năng động, phù hợp học sinh và dân văn phòng.	tui_7.jpg	2026-08-29 07:09:22.085396
100	Quần jean nam ống đứng	11	480000.00	\N	Phong cách cổ điển, dễ phối đồ.	quanjeannam_1.jpg	2026-08-29 07:09:22.085396
101	Quần jean nam rách gối	11	510000.00	\N	Trẻ trung, năng động.	quanjeannam_2.jpg	2026-08-29 07:09:22.085396
102	Quần jean nam skinny	11	520000.00	\N	Co giãn tốt, ôm dáng.	quanjeannam_3.jpg	2026-08-29 07:09:22.085396
103	Quần jean nam xanh nhạt	11	490000.00	\N	Mềm mại, thoải mái khi mặc.	quanjeannam_4.jpg	2026-08-29 07:09:22.085396
104	Quần jean nam dáng suông	11	530000.00	\N	Hợp mốt, năng động.	quanjeannam_5.jpg	2026-08-29 07:09:22.085396
105	Quần denim nam. Slim	11	589000.00	\N	Phong cách cổ điển, dễ phối đồ.	quanjeannam_6.jpg	2026-08-29 07:09:22.085396
106	Quần denim nam. Baggy	11	638000.00	\N	Trẻ trung, năng động.	quanjeannam_7.jpg	2026-08-29 07:09:22.085396
107	Quần denim nam. Regular	11	560000.00	\N	Co giãn tốt, ôm dáng.	quanjeannam_8.jpg	2026-08-29 07:09:22.085396
108	Quần denim nam thêu nhỏ. Straight	11	638000.00	\N	Mềm mại, thoải mái khi mặc.	quanjeannam_9.jpg	2026-08-29 07:09:22.085396
109	Quần denim nam thêu nhỏ. Straight	11	650000.00	\N	Hợp mốt, năng động.	quanjeannam_10.jpg	2026-08-29 07:09:22.085396
110	Quần short kaki nam	12	370000.00	\N	Chất liệu nhẹ, dễ vận động.	quanshortnam_1.jpg	2026-08-29 07:09:22.085396
111	Quần short jean nam	12	390000.00	\N	Thiết kế trẻ trung, năng động.	quanshortnam_2.jpg	2026-08-29 07:09:22.085396
112	Quần short thể thao nam	12	350000.00	\N	Co giãn, thoáng khí.	quanshortnam_3.jpg	2026-08-29 07:09:22.085396
113	Quần short túi hộp nam	12	410000.00	\N	Tiện dụng, phong cách đường phố.	quanshortnam_4.jpg	2026-08-29 07:09:22.085396
114	Quần short vải linen nam	12	360000.00	\N	Thoáng mát, mềm mại.	quanshortnam_5.jpg	2026-08-29 07:09:22.085396
115	Quần short khaki nam. Straight	12	471000.00	\N	Chất liệu nhẹ, dễ vận động.	quanshortnam_6.jpg	2026-08-29 07:09:22.085396
116	Quần short nam túi hộp cargo.Straight	12	395000.00	\N	Thiết kế trẻ trung, năng động.	quanshortnam_7.jpg	2026-08-29 07:09:22.085396
117	Quần short nam túi khoá kéo.Relax	12	250000.00	\N	Co giãn, thoáng khí.	quanshortnam_8.jpg	2026-08-29 07:09:22.085396
118	Quần short nam túi khoá kéo sườn.Straight	12	415000.00	\N	Tiện dụng, phong cách đường phố.	quanshortnam_9.jpg	2026-08-29 07:09:22.085396
119	Quần Short Cargo Nam Cotton Spandex Form Loose	12	520000.00	\N	Thoáng mát, mềm mại.	quanshortnam_10.jpg	2026-08-29 07:09:22.085396
120	Quần tây nam đen ôm	13	520000.00	\N	Lịch sự, phù hợp công sở.	quantaynam_1.jpg	2026-08-29 07:09:22.085396
121	Quần tây nam xanh than	13	540000.00	\N	Form slimfit, dễ phối áo.	quantaynam_2.jpg	2026-08-29 07:09:22.085396
122	Quần tây nam vải co giãn	13	560000.00	\N	Thoải mái cả ngày dài.	quantaynam_3.jpg	2026-08-29 07:09:22.085396
123	Quần tây nam kẻ caro	13	580000.00	\N	Phong cách châu Âu, sang trọng.	quantaynam_4.jpg	2026-08-29 07:09:22.085396
124	Quần tây nam xám nhạt	13	550000.00	\N	Tinh tế, thanh lịch.	quantaynam_5.jpg	2026-08-29 07:09:22.085396
125	Váy xòe tay phồng	14	490000.00	\N	Phong cách công chúa nhẹ nhàng.	vay_1.jpg	2026-08-29 07:09:22.085396
126	Váy chữ A caro	14	460000.00	\N	Trẻ trung, dễ phối áo.	vay_2.jpg	2026-08-29 07:09:22.085396
127	Váy hai dây satin	14	520000.00	\N	Mềm mịn, quyến rũ.	vay_3.jpg	2026-08-29 07:09:22.085396
128	Váy midi công sở	14	550000.00	\N	Phù hợp làm việc và dạo phố.	vay_4.jpg	2026-08-29 07:09:22.085396
129	Váy hoa vintage	14	500000.00	\N	Họa tiết cổ điển, dịu dàng.	vay_5.jpg	2026-08-29 07:09:22.085396
130	Váy Nữ Dài Vải Dù Lưng Thun Xẻ Tà 2 Bên	14	569000.00	\N	Phong cách công chúa nhẹ nhàng.	vay_6.jpg	2026-08-29 07:09:22.085396
131	váy nữ cotton lưng thun hai lớp Aline	14	383000.00	\N	Trẻ trung, dễ phối áo.	vay_7.jpg	2026-08-29 07:09:22.085396
132	Váy Denim Nữ Ngắn Thắt Lưng Form A Line	14	349000.00	\N	Phù hợp làm việc và dạo phố.	vay_8.jpg	2026-08-29 07:09:22.085396
133	Chân Váy Nữ Dài Xếp Ly 2 Lớp Mềm Mịn Form A Line	14	667000.00	\N	Họa tiết cổ điển, dịu dàng.	vay_10.jpg	2026-08-29 07:09:22.085396
136	Áo thun 3 lỗ	7	200000.00	\N	Áo thun 3 lỗ mát mẻ vào mùa hè	311cfa45-9b16-4036-a17f-0be1c91e79ca.jpg	2026-09-04 14:17:49.933975
\.


--
-- TOC entry 3578 (class 0 OID 16791)
-- Dependencies: 232
-- Data for Name: sanphambienthe; Type: TABLE DATA; Schema: public; Owner: cuong
--

COPY public.sanphambienthe (mabienthe, masp, masize, mamau, soluongton, giaban) FROM stdin;
781	1	1	19	12	650000.00
782	1	2	15	8	650000.00
785	2	2	9	15	780000.00
786	2	1	12	8	780000.00
789	3	5	4	8	720000.00
790	4	3	14	5	950000.00
791	4	1	2	3	950000.00
792	4	3	4	2	950000.00
793	5	2	4	10	690000.00
794	5	2	7	12	690000.00
795	5	1	16	8	690000.00
796	6	4	3	10	569000.00
797	6	5	6	12	569000.00
798	6	1	7	8	569000.00
799	7	2	10	15	785000.00
800	7	3	15	10	785000.00
801	7	2	6	5	785000.00
802	8	4	10	12	981000.00
803	8	1	20	15	981000.00
804	8	4	13	10	981000.00
805	9	2	14	20	686000.00
806	9	4	2	15	686000.00
807	9	1	10	10	686000.00
808	10	3	6	12	512000.00
809	10	5	8	15	512000.00
810	10	3	11	10	512000.00
812	11	3	1	7	890000.00
813	11	2	4	4	890000.00
814	11	1	7	2	890000.00
815	11	4	9	1	890000.00
817	12	1	10	12	590000.00
818	12	2	15	8	590000.00
819	13	3	6	10	620000.00
820	13	1	8	12	620000.00
821	13	2	16	8	620000.00
822	14	1	1	5	970000.00
823	14	4	5	4	970000.00
824	14	2	18	3	970000.00
825	15	4	20	10	650000.00
826	15	1	7	12	650000.00
827	15	3	1	8	650000.00
828	16	5	3	8	490000.00
829	16	3	5	7	490000.00
830	16	1	8	3	490000.00
831	17	2	1	12	501000.00
832	17	3	11	10	501000.00
833	17	2	16	8	501000.00
834	18	1	19	10	686000.00
835	18	4	10	8	686000.00
836	18	5	20	6	686000.00
837	19	1	12	5	149000.00
838	19	2	16	4	149000.00
839	19	3	19	3	149000.00
840	20	1	14	20	490000.00
841	20	2	12	15	490000.00
842	20	1	11	10	490000.00
843	21	1	1	5	480000.00
844	21	3	12	7	480000.00
845	21	1	2	6	480000.00
846	21	2	4	4	480000.00
847	21	1	6	3	480000.00
848	22	4	7	6	420000.00
849	22	2	9	8	420000.00
850	22	1	1	7	420000.00
851	22	3	6	5	420000.00
852	23	1	7	7	460000.00
853	23	5	10	6	460000.00
854	23	3	19	5	460000.00
855	24	1	16	8	390000.00
856	24	3	12	10	390000.00
857	24	4	13	8	390000.00
858	25	2	17	6	440000.00
859	25	1	16	7	440000.00
860	25	5	4	6	440000.00
861	25	1	1	5	440000.00
862	26	1	8	10	274000.00
863	26	2	16	15	274000.00
864	26	3	6	12	274000.00
865	26	1	1	8	274000.00
866	26	3	20	5	274000.00
867	27	1	1	10	422000.00
868	27	4	4	8	422000.00
869	27	2	7	6	422000.00
870	28	1	12	10	350000.00
871	28	2	3	15	350000.00
872	28	3	19	10	350000.00
873	28	4	7	5	350000.00
874	28	5	18	3	350000.00
876	29	3	20	8	380000.00
877	29	4	14	6	380000.00
878	30	1	1	10	320000.00
879	30	2	11	12	320000.00
880	30	3	5	8	320000.00
881	31	2	13	8	370000.00
882	31	3	10	6	370000.00
883	31	4	6	5	370000.00
884	32	2	9	10	400000.00
885	32	3	2	8	400000.00
886	32	4	17	5	400000.00
887	33	2	8	10	687000.00
888	33	3	15	12	687000.00
889	33	4	16	8	687000.00
890	34	2	12	8	589000.00
891	34	3	3	6	589000.00
892	34	4	19	5	589000.00
893	35	1	7	8	349000.00
894	35	2	18	10	349000.00
895	35	3	4	7	349000.00
896	36	2	20	5	618000.00
897	36	3	14	4	618000.00
898	36	4	1	3	618000.00
899	37	2	11	8	490000.00
900	37	3	5	6	490000.00
901	37	4	13	5	490000.00
902	38	1	10	10	420000.00
903	38	2	6	12	420000.00
904	38	3	9	8	420000.00
905	38	4	2	5	420000.00
906	39	2	17	6	450000.00
907	39	3	8	5	450000.00
908	39	4	15	4	450000.00
909	40	2	16	8	480000.00
910	40	3	12	6	480000.00
911	40	4	3	4	480000.00
912	41	2	19	8	440000.00
913	41	3	7	6	440000.00
914	41	4	18	5	440000.00
811	11	2	14	0	890000.00
780	1	3	1	14	650000.00
783	1	1	20	5	650000.00
787	3	4	1	12	720000.00
816	12	5	11	10	590000.00
784	2	4	3	10	780000.00
915	42	2	4	6	460000.00
916	42	3	20	5	460000.00
917	42	4	14	4	460000.00
918	43	2	1	10	667000.00
919	43	3	11	8	667000.00
920	43	4	5	6	667000.00
921	44	2	13	6	540000.00
922	44	3	10	5	540000.00
923	44	4	6	4	540000.00
924	45	2	9	5	399000.00
925	45	3	2	4	399000.00
926	45	4	17	3	399000.00
927	46	2	8	6	349000.00
928	46	3	15	5	349000.00
929	46	4	16	4	349000.00
930	47	2	12	6	469000.00
931	47	3	3	5	469000.00
932	47	4	19	4	469000.00
933	48	1	7	5	390000.00
934	48	2	18	7	390000.00
935	48	3	4	6	390000.00
936	49	2	20	6	420000.00
937	49	3	14	5	420000.00
938	49	4	1	4	420000.00
939	50	1	11	8	370000.00
940	50	2	5	10	370000.00
941	50	3	13	7	370000.00
942	51	2	10	6	410000.00
943	51	3	6	5	410000.00
944	51	4	9	4	410000.00
945	52	2	2	5	430000.00
946	52	3	17	4	430000.00
947	52	4	8	3	430000.00
948	53	2	15	10	249000.00
949	53	3	16	8	249000.00
950	53	4	12	6	249000.00
951	54	2	3	6	441000.00
952	54	3	19	5	441000.00
953	54	4	7	4	441000.00
954	55	2	18	8	471000.00
955	55	3	4	7	471000.00
956	55	4	20	6	471000.00
957	56	2	14	6	308000.00
958	56	3	1	5	308000.00
959	56	4	11	4	308000.00
960	57	2	5	6	431000.00
961	57	3	13	5	431000.00
962	57	4	10	4	431000.00
963	58	1	6	10	250000.00
964	58	2	9	15	250000.00
965	58	3	2	12	250000.00
966	58	4	17	8	250000.00
968	59	2	15	12	270000.00
969	59	3	16	10	270000.00
970	60	1	12	8	260000.00
971	60	2	3	10	260000.00
972	60	3	19	7	260000.00
973	61	2	7	8	290000.00
974	61	3	18	6	290000.00
975	61	4	4	5	290000.00
976	62	1	20	10	240000.00
977	62	2	14	12	240000.00
978	62	3	1	10	240000.00
979	63	2	11	10	638000.00
980	63	3	5	8	638000.00
981	63	4	13	6	638000.00
982	64	2	10	8	589000.00
983	64	3	6	6	589000.00
984	64	4	9	5	589000.00
985	65	2	2	6	392000.00
986	65	3	17	5	392000.00
987	65	4	8	4	392000.00
988	66	1	15	10	147000.00
989	66	2	16	12	147000.00
990	66	3	12	8	147000.00
991	67	2	3	10	441000.00
992	67	3	19	8	441000.00
993	67	4	7	6	441000.00
994	68	1	18	8	260000.00
995	68	2	4	10	260000.00
996	68	3	20	7	260000.00
997	69	1	14	7	240000.00
998	69	2	1	8	240000.00
999	69	3	11	6	240000.00
1000	70	1	5	6	250000.00
1001	70	2	13	8	250000.00
1002	70	3	10	5	250000.00
1003	71	1	6	6	230000.00
1004	71	2	9	7	230000.00
1005	71	3	2	5	230000.00
1006	72	2	17	8	270000.00
1007	72	3	8	6	270000.00
1008	72	4	15	5	270000.00
1009	73	2	16	10	441000.00
1010	73	3	12	8	441000.00
1011	73	4	3	6	441000.00
1012	74	2	19	8	471000.00
1013	74	3	7	6	471000.00
1014	74	4	18	5	471000.00
1015	75	2	4	6	294000.00
1016	75	3	20	5	294000.00
1017	75	4	14	4	294000.00
1018	76	2	1	6	343000.00
1019	76	3	11	5	343000.00
1020	76	4	5	4	343000.00
1021	77	2	13	8	342000.00
1022	77	3	10	6	342000.00
1023	77	4	6	5	342000.00
1024	78	1	9	5	580000.00
1025	78	2	2	7	580000.00
1026	78	3	17	6	580000.00
1027	79	2	8	5	620000.00
1028	79	3	15	4	620000.00
1029	79	4	16	3	620000.00
1030	80	2	12	6	540000.00
1031	80	3	3	5	540000.00
1032	80	4	19	4	540000.00
1033	81	2	7	3	850000.00
1034	81	3	18	2	850000.00
1035	81	4	4	1	850000.00
1036	82	2	20	6	590000.00
1037	82	3	14	5	590000.00
1038	82	4	1	4	590000.00
1039	83	2	11	6	378000.00
1040	83	3	5	5	378000.00
1041	83	4	13	4	378000.00
1042	84	2	10	5	569000.00
1043	84	3	6	4	569000.00
1044	84	4	9	3	569000.00
1045	85	2	2	6	199000.00
1046	85	3	17	5	199000.00
1047	85	4	8	4	199000.00
1048	86	2	15	3	638000.00
1049	86	3	16	2	638000.00
1050	86	4	12	1	638000.00
1051	87	2	3	6	189000.00
1052	87	3	19	5	189000.00
1053	87	4	7	4	189000.00
1054	88	6	14	30	380000.00
1055	89	6	11	25	420000.00
1056	90	6	11	35	250000.00
1057	91	6	16	28	340000.00
1058	92	6	14	26	460000.00
1059	93	6	14	30	38000.00
1060	94	6	14	25	42000.00
1061	95	6	16	35	25000.00
1062	96	6	16	28	34000.00
1063	97	6	11	26	46000.00
1064	98	6	16	28	49000.00
1065	99	6	17	26	780000.00
1066	100	2	10	8	480000.00
1067	100	3	11	7	480000.00
1068	100	4	4	5	480000.00
1069	101	2	8	6	510000.00
1070	101	3	9	5	510000.00
1071	101	4	13	4	510000.00
1072	102	2	7	7	520000.00
1073	102	3	19	6	520000.00
1074	102	4	20	5	520000.00
1075	103	2	18	8	490000.00
1076	103	3	16	6	490000.00
1077	103	4	13	5	490000.00
1078	104	2	11	7	530000.00
1079	104	3	10	6	530000.00
1080	104	4	6	5	530000.00
1081	105	2	1	8	589000.00
1082	105	3	11	7	589000.00
1083	105	4	2	6	589000.00
1084	106	2	5	6	638000.00
1085	106	3	4	5	638000.00
1086	106	4	10	4	638000.00
1087	107	2	14	7	560000.00
1088	107	3	17	6	560000.00
1089	107	4	18	5	560000.00
1090	108	2	12	8	638000.00
1091	108	3	9	7	638000.00
1092	108	4	20	6	638000.00
1093	109	2	9	7	650000.00
1094	109	3	5	6	650000.00
1095	109	4	9	5	650000.00
1096	110	2	4	8	370000.00
1097	110	3	15	7	370000.00
1098	110	4	9	6	370000.00
1099	111	2	1	7	390000.00
1100	111	3	18	6	390000.00
1101	111	4	6	5	390000.00
1102	112	2	12	8	350000.00
1103	112	3	7	7	350000.00
1104	112	4	3	6	350000.00
1105	113	2	19	6	410000.00
1106	113	3	2	5	410000.00
1107	113	4	13	4	410000.00
1108	114	2	10	7	360000.00
1109	114	3	5	6	360000.00
1110	114	4	8	5	360000.00
1111	115	2	14	8	471000.00
1112	115	3	20	7	471000.00
1113	115	4	11	6	471000.00
1114	116	2	2	7	395000.00
1115	116	3	17	6	395000.00
1116	116	4	1	5	395000.00
1117	117	2	7	8	250000.00
1118	117	3	3	7	250000.00
1119	117	4	16	6	250000.00
1120	118	2	18	6	415000.00
1121	118	3	12	5	415000.00
1122	118	4	4	4	415000.00
1123	119	2	5	7	520000.00
1124	119	3	8	6	520000.00
1125	119	4	15	5	520000.00
1126	120	2	3	10	520000.00
1127	120	3	14	10	520000.00
1128	120	4	7	10	520000.00
1129	121	2	11	8	540000.00
1130	121	3	5	8	540000.00
1132	122	2	9	7	560000.00
1133	122	3	16	8	560000.00
1134	122	4	12	7	560000.00
1135	123	2	10	6	580000.00
1136	123	3	2	6	580000.00
1137	123	4	17	6	580000.00
1138	124	2	1	8	550000.00
1139	124	3	19	8	550000.00
1140	124	4	4	8	550000.00
1141	125	1	6	5	490000.00
1142	125	2	2	5	490000.00
1143	125	3	18	5	490000.00
1144	126	2	9	6	460000.00
1145	126	3	14	6	460000.00
1146	126	4	20	6	460000.00
1147	127	2	1	6	520000.00
1148	127	3	8	6	520000.00
1149	127	4	13	6	520000.00
1150	128	2	7	6	550000.00
1151	128	3	12	6	550000.00
1152	128	4	3	6	550000.00
1153	129	2	16	6	500000.00
1154	129	3	5	7	500000.00
1155	129	4	15	7	500000.00
1156	130	2	20	6	569000.00
1157	130	3	9	6	569000.00
1158	130	4	11	6	569000.00
1159	131	2	4	6	383000.00
1160	131	3	17	6	383000.00
1161	131	4	7	6	383000.00
1162	132	2	19	6	349000.00
1163	132	3	8	6	349000.00
1164	132	4	2	6	349000.00
1165	133	2	14	6	667000.00
1166	133	3	6	6	667000.00
1167	133	4	10	6	667000.00
1131	121	4	18	9	540000.00
779	1	1	10	30	650000.00
875	29	2	4	9	380000.00
967	59	1	8	8	270000.00
788	3	1	5	10	720000.00
\.


--
-- TOC entry 3574 (class 0 OID 16772)
-- Dependencies: 228
-- Data for Name: size; Type: TABLE DATA; Schema: public; Owner: cuong
--

COPY public.size (masize, tensize) FROM stdin;
1	S
2	M
3	L
4	XL
5	XXL
6	Free Size
\.


--
-- TOC entry 3588 (class 0 OID 17014)
-- Dependencies: 242
-- Data for Name: thongbao; Type: TABLE DATA; Schema: public; Owner: cuong
--

COPY public.thongbao (mathongbao, dadoc, madonhang, thoigian, trangthai, id) FROM stdin;
1	t	4	2026-09-08 16:38:38.693262	Hoàn thành	3
2	f	3	2026-09-08 16:39:25.282117	Hủy	3
3	f	2	2026-09-08 16:39:45.687252	Đang giao	3
4	f	11	2026-09-08 16:55:41.712165	Hủy	7
5	f	2	2026-09-15 08:28:29.331024	Hoàn thành	3
6	f	2	2026-09-15 08:53:11.212948	Đang giao	3
7	f	13	2026-09-18 09:26:37.063805	Hủy	3
\.


--
-- TOC entry 3606 (class 0 OID 0)
-- Dependencies: 219
-- Name: blacklisted_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cuong
--

SELECT pg_catalog.setval('public.blacklisted_tokens_id_seq', 2, true);


--
-- TOC entry 3607 (class 0 OID 0)
-- Dependencies: 239
-- Name: chitietdonhang_machitiet_seq; Type: SEQUENCE SET; Schema: public; Owner: cuong
--

SELECT pg_catalog.setval('public.chitietdonhang_machitiet_seq', 13, true);


--
-- TOC entry 3608 (class 0 OID 0)
-- Dependencies: 223
-- Name: danhmuc_madm_seq; Type: SEQUENCE SET; Schema: public; Owner: cuong
--

SELECT pg_catalog.setval('public.danhmuc_madm_seq', 15, true);


--
-- TOC entry 3609 (class 0 OID 0)
-- Dependencies: 237
-- Name: donhang_madonhang_seq; Type: SEQUENCE SET; Schema: public; Owner: cuong
--

SELECT pg_catalog.setval('public.donhang_madonhang_seq', 13, true);


--
-- TOC entry 3610 (class 0 OID 0)
-- Dependencies: 235
-- Name: giohang_magiohang_seq; Type: SEQUENCE SET; Schema: public; Owner: cuong
--

SELECT pg_catalog.setval('public.giohang_magiohang_seq', 17, true);


--
-- TOC entry 3611 (class 0 OID 0)
-- Dependencies: 233
-- Name: hinhanhsanpham_mahinhanh_seq; Type: SEQUENCE SET; Schema: public; Owner: cuong
--

SELECT pg_catalog.setval('public.hinhanhsanpham_mahinhanh_seq', 15, true);


--
-- TOC entry 3612 (class 0 OID 0)
-- Dependencies: 243
-- Name: lienhe_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cuong
--

SELECT pg_catalog.setval('public.lienhe_id_seq', 47, true);


--
-- TOC entry 3613 (class 0 OID 0)
-- Dependencies: 229
-- Name: mausac_mamau_seq; Type: SEQUENCE SET; Schema: public; Owner: cuong
--

SELECT pg_catalog.setval('public.mausac_mamau_seq', 20, true);


--
-- TOC entry 3614 (class 0 OID 0)
-- Dependencies: 221
-- Name: nguoidung_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cuong
--

SELECT pg_catalog.setval('public.nguoidung_id_seq', 13, true);


--
-- TOC entry 3615 (class 0 OID 0)
-- Dependencies: 225
-- Name: sanpham_masp_seq; Type: SEQUENCE SET; Schema: public; Owner: cuong
--

SELECT pg_catalog.setval('public.sanpham_masp_seq', 136, true);


--
-- TOC entry 3616 (class 0 OID 0)
-- Dependencies: 231
-- Name: sanphambienthe_mabienthe_seq; Type: SEQUENCE SET; Schema: public; Owner: cuong
--

SELECT pg_catalog.setval('public.sanphambienthe_mabienthe_seq', 1167, true);


--
-- TOC entry 3617 (class 0 OID 0)
-- Dependencies: 227
-- Name: size_masize_seq; Type: SEQUENCE SET; Schema: public; Owner: cuong
--

SELECT pg_catalog.setval('public.size_masize_seq', 6, true);


--
-- TOC entry 3618 (class 0 OID 0)
-- Dependencies: 241
-- Name: thongbao_mathongbao_seq; Type: SEQUENCE SET; Schema: public; Owner: cuong
--

SELECT pg_catalog.setval('public.thongbao_mathongbao_seq', 7, true);


--
-- TOC entry 3378 (class 2606 OID 16523)
-- Name: blacklisted_tokens blacklisted_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.blacklisted_tokens
    ADD CONSTRAINT blacklisted_tokens_pkey PRIMARY KEY (id);


--
-- TOC entry 3402 (class 2606 OID 16888)
-- Name: chitietdonhang chitietdonhang_pkey; Type: CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.chitietdonhang
    ADD CONSTRAINT chitietdonhang_pkey PRIMARY KEY (machitiet);


--
-- TOC entry 3386 (class 2606 OID 16752)
-- Name: danhmuc danhmuc_pkey; Type: CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.danhmuc
    ADD CONSTRAINT danhmuc_pkey PRIMARY KEY (madm);


--
-- TOC entry 3400 (class 2606 OID 16871)
-- Name: donhang donhang_pkey; Type: CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.donhang
    ADD CONSTRAINT donhang_pkey PRIMARY KEY (madonhang);


--
-- TOC entry 3398 (class 2606 OID 16846)
-- Name: giohang giohang_pkey; Type: CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.giohang
    ADD CONSTRAINT giohang_pkey PRIMARY KEY (magiohang);


--
-- TOC entry 3396 (class 2606 OID 16828)
-- Name: hinhanhsanpham hinhanhsanpham_pkey; Type: CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.hinhanhsanpham
    ADD CONSTRAINT hinhanhsanpham_pkey PRIMARY KEY (mahinhanh);


--
-- TOC entry 3406 (class 2606 OID 17038)
-- Name: lienhe lienhe_pkey; Type: CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.lienhe
    ADD CONSTRAINT lienhe_pkey PRIMARY KEY (id);


--
-- TOC entry 3392 (class 2606 OID 16789)
-- Name: mausac mausac_pkey; Type: CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.mausac
    ADD CONSTRAINT mausac_pkey PRIMARY KEY (mamau);


--
-- TOC entry 3382 (class 2606 OID 16972)
-- Name: nguoidung nguoidung_email_key; Type: CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.nguoidung
    ADD CONSTRAINT nguoidung_email_key UNIQUE (email);


--
-- TOC entry 3384 (class 2606 OID 16741)
-- Name: nguoidung nguoidung_pkey; Type: CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.nguoidung
    ADD CONSTRAINT nguoidung_pkey PRIMARY KEY (id);


--
-- TOC entry 3388 (class 2606 OID 16765)
-- Name: sanpham sanpham_pkey; Type: CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.sanpham
    ADD CONSTRAINT sanpham_pkey PRIMARY KEY (masp);


--
-- TOC entry 3394 (class 2606 OID 16803)
-- Name: sanphambienthe sanphambienthe_pkey; Type: CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.sanphambienthe
    ADD CONSTRAINT sanphambienthe_pkey PRIMARY KEY (mabienthe);


--
-- TOC entry 3390 (class 2606 OID 16779)
-- Name: size size_pkey; Type: CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.size
    ADD CONSTRAINT size_pkey PRIMARY KEY (masize);


--
-- TOC entry 3404 (class 2606 OID 17024)
-- Name: thongbao thongbao_pkey; Type: CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.thongbao
    ADD CONSTRAINT thongbao_pkey PRIMARY KEY (mathongbao);


--
-- TOC entry 3380 (class 2606 OID 16525)
-- Name: blacklisted_tokens ukibvoggbe8ijw4l7xyyotp5n7g; Type: CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.blacklisted_tokens
    ADD CONSTRAINT ukibvoggbe8ijw4l7xyyotp5n7g UNIQUE (token);


--
-- TOC entry 3415 (class 2606 OID 16894)
-- Name: chitietdonhang chitietdonhang_mabienthe_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.chitietdonhang
    ADD CONSTRAINT chitietdonhang_mabienthe_fkey FOREIGN KEY (mabienthe) REFERENCES public.sanphambienthe(mabienthe);


--
-- TOC entry 3416 (class 2606 OID 16889)
-- Name: chitietdonhang chitietdonhang_madonhang_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.chitietdonhang
    ADD CONSTRAINT chitietdonhang_madonhang_fkey FOREIGN KEY (madonhang) REFERENCES public.donhang(madonhang) ON DELETE CASCADE;


--
-- TOC entry 3414 (class 2606 OID 16872)
-- Name: donhang donhang_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.donhang
    ADD CONSTRAINT donhang_id_fkey FOREIGN KEY (id) REFERENCES public.nguoidung(id) ON DELETE CASCADE;


--
-- TOC entry 3417 (class 2606 OID 17025)
-- Name: thongbao fkjnuul8k0pg2a4iuttoxicvmc5; Type: FK CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.thongbao
    ADD CONSTRAINT fkjnuul8k0pg2a4iuttoxicvmc5 FOREIGN KEY (id) REFERENCES public.nguoidung(id);


--
-- TOC entry 3412 (class 2606 OID 16847)
-- Name: giohang giohang_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.giohang
    ADD CONSTRAINT giohang_id_fkey FOREIGN KEY (id) REFERENCES public.nguoidung(id) ON DELETE CASCADE;


--
-- TOC entry 3413 (class 2606 OID 16852)
-- Name: giohang giohang_mabienthe_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.giohang
    ADD CONSTRAINT giohang_mabienthe_fkey FOREIGN KEY (mabienthe) REFERENCES public.sanphambienthe(mabienthe) ON DELETE CASCADE;


--
-- TOC entry 3411 (class 2606 OID 16829)
-- Name: hinhanhsanpham hinhanhsanpham_masp_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.hinhanhsanpham
    ADD CONSTRAINT hinhanhsanpham_masp_fkey FOREIGN KEY (masp) REFERENCES public.sanpham(masp) ON DELETE CASCADE;


--
-- TOC entry 3407 (class 2606 OID 16766)
-- Name: sanpham sanpham_madm_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.sanpham
    ADD CONSTRAINT sanpham_madm_fkey FOREIGN KEY (madm) REFERENCES public.danhmuc(madm) ON DELETE SET NULL;


--
-- TOC entry 3408 (class 2606 OID 16814)
-- Name: sanphambienthe sanphambienthe_mamau_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.sanphambienthe
    ADD CONSTRAINT sanphambienthe_mamau_fkey FOREIGN KEY (mamau) REFERENCES public.mausac(mamau);


--
-- TOC entry 3409 (class 2606 OID 16809)
-- Name: sanphambienthe sanphambienthe_masize_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.sanphambienthe
    ADD CONSTRAINT sanphambienthe_masize_fkey FOREIGN KEY (masize) REFERENCES public.size(masize);


--
-- TOC entry 3410 (class 2606 OID 16804)
-- Name: sanphambienthe sanphambienthe_masp_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cuong
--

ALTER TABLE ONLY public.sanphambienthe
    ADD CONSTRAINT sanphambienthe_masp_fkey FOREIGN KEY (masp) REFERENCES public.sanpham(masp) ON DELETE CASCADE;


-- Completed on 2026-09-22 10:19:08

--
-- PostgreSQL database dump complete
--

-- 1. Insert 1,000,000 dòng vào bảng sanpham
WITH new_products AS (
    INSERT INTO public.sanpham (tensp, madm, giaban, giakhuyenmai, mota, hinhanh, ngaythem)
    SELECT 
        'Sản phẩm thử nghiệm ' || i AS tensp,
        floor(random() * 15 + 1)::int AS madm, -- Ngẫu nhiên danh mục từ 1 đến 15
        (floor(random() * 90 + 10) * 10000)::numeric(12,2) AS giaban, -- Giá từ 100k đến 1tr
        CASE 
            WHEN random() > 0.5 THEN (floor(random() * 8 + 1) * 10000)::numeric(12,2) 
            ELSE NULL 
        END AS giakhuyenmai,
        'Mô tả chi tiết tự động cho sản phẩm mã ' || i AS mota,
        'product_' || ((i % 15) + 1) || '.jpg' AS hinhanh,
        NOW() - (random() * interval '365 days') AS ngaythem
    FROM generate_series(1, 1000000) AS s(i)
    RETURNING masp, giaban
)
-- 2. Insert đồng thời các biến thể tương ứng cho 1,000,000 sản phẩm vừa tạo
INSERT INTO public.sanphambienthe (masp, masize, mamau, soluongton, giaban)
SELECT 
    np.masp,
    floor(random() * 6 + 1)::int AS masize,   -- Masize từ 1 đến 6
    floor(random() * 20 + 1)::int AS mamau,  -- Mamau từ 1 đến 20
    floor(random() * 100 + 1)::int AS soluongton,
    np.giaban
FROM new_products np
CROSS JOIN LATERAL generate_series(1, floor(random() * 3 + 1)::int); -- 1 đến 3 biến thể mỗi SP


-- Kích hoạt extension hỗ trợ tìm kiếm chuỗi con và fuzzy search
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Tạo GIN Index trên cột tensp
CREATE INDEX idx_sanpham_tensp_trgm ON public.sanpham USING gin (tensp gin_trgm_ops);

SELECT masp, tensp, giaban, hinhanh, diem_danh_gia_tb
FROM public.sanpham
WHERE tensp ILIKE '%khoác%'
ORDER BY diem_danh_gia_tb DESC
LIMIT 20 OFFSET 0;

------- Tạo bảng Đánh giá
CREATE TABLE public.danhgia (
    madanhgia SERIAL PRIMARY KEY,
    masp INT NOT NULL REFERENCES public.sanpham(masp) ON DELETE CASCADE,
    id_nguoidung INT NOT NULL REFERENCES public.nguoidung(id) ON DELETE CASCADE,
    sodiem SMALLINT NOT NULL CHECK (sodiem BETWEEN 1 AND 5),
    binhluan TEXT,
    ngaytao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index để tìm nhanh review theo sản phẩm
CREATE INDEX idx_danhgia_masp ON public.danhgia(masp);

ALTER TABLE public.sanpham 
ADD COLUMN diem_danh_gia_tb NUMERIC(2,1) DEFAULT 0.0,
ADD COLUMN so_luot_danh_gia INT DEFAULT 0;

-- Index phục vụ ORDER BY điểm số giảm dần
CREATE INDEX idx_sanpham_rating ON public.sanpham (diem_danh_gia_tb DESC, masp DESC);

------------ Tạo Trigger tự động cập nhật Rating
CREATE OR REPLACE FUNCTION public.cap_nhat_rating_sanpham()
RETURNS TRIGGER AS $$
DECLARE
    v_masp INT;
BEGIN
    IF (TG_OP = 'DELETE') THEN
        v_masp := OLD.masp;
    ELSE
        v_masp := NEW.masp;
    END IF;

    UPDATE public.sanpham
    SET 
        diem_danh_gia_tb = COALESCE((SELECT ROUND(AVG(sodiem), 1) FROM public.danhgia WHERE masp = v_masp), 0.0),
        so_luot_danh_gia = (SELECT COUNT(*) FROM public.danhgia WHERE masp = v_masp)
    WHERE masp = v_masp;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_cap_nhat_rating
AFTER INSERT OR UPDATE OR DELETE ON public.danhgia
FOR EACH ROW
EXECUTE FUNCTION public.cap_nhat_rating_sanpham();


\unrestrict IkNzG5k0Fhobw2VTa9WfFhFlAtUqZQ6tJntnl46NCOtrmQF7tH96uqOg8B3IvG8

